SELECT 
    SITE.SiteID,
    SITE.`Site name`,
    AVG(OBSERVATION.PM2_5) AS Average_PM2_5,
    AVG(OBSERVATION.VPM2_5) AS Average_VPM2_5
FROM 
    OBSERVATION
JOIN 
    SITE ON OBSERVATION.SITE_SiteID = SITE.SiteID
WHERE 
    YEAR(OBSERVATION.Date_time) = 2022
    AND HOUR(OBSERVATION.Date_time) = 08
GROUP BY 
    SITE.SiteID, SITE.`Site name`;

